<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class Szvegek {
	private $szvegek_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'szvegek_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'szvegek_page_init' ) );
	}

	public function szvegek_add_plugin_page() {
		add_submenu_page(
      'vue-court-reservation',
			'Szövegek', // page_title
			'Szövegek', // menu_title
			'manage_options', // capability
			'szvegek', // menu_slug
			array( $this, 'szvegek_create_admin_page' ) // function
		);
	}

	public function szvegek_create_admin_page() {
		$this->szvegek_options = get_option( 'szvegek_option_name' ); ?>

		<div class="wrap">
			<h2>Szövegek</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'szvegek_option_group' );
					do_settings_sections( 'szvegek-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function szvegek_page_init() {
		register_setting(
			'szvegek_option_group', // option_group
			'szvegek_option_name', // option_name
			array( $this, 'szvegek_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'szvegek_setting_section', // id
			'Settings', // title
			array( $this, 'szvegek_section_info' ), // callback
			'szvegek-admin' // page
		);

		add_settings_field(
			'sikeres_foglals_popup_0', // id
			'Sikeres foglalás popup', // title
			array( $this, 'sikeres_foglals_popup_0_callback' ), // callback
			'szvegek-admin', // page
			'szvegek_setting_section' // section
		);

		add_settings_field(
			'foglals_trlse_popup_1', // id
			'Foglalás törlése popup', // title
			array( $this, 'foglals_trlse_popup_1_callback' ), // callback
			'szvegek-admin', // page
			'szvegek_setting_section' // section
		);

		add_settings_field(
			'last_minute_tooltip_2', // id
			'Last minute tooltip', // title
			array( $this, 'last_minute_tooltip_2_callback' ), // callback
			'szvegek-admin', // page
			'szvegek_setting_section' // section
		);

		add_settings_field(
			'stteds_tooltip_3', // id
			'Sötétedés tooltip', // title
			array( $this, 'stteds_tooltip_3_callback' ), // callback
			'szvegek-admin', // page
			'szvegek_setting_section' // section
		);
	}

	public function szvegek_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['sikeres_foglals_popup_0'] ) ) {
			$sanitary_values['sikeres_foglals_popup_0'] = esc_textarea( $input['sikeres_foglals_popup_0'] );
		}

		if ( isset( $input['foglals_trlse_popup_1'] ) ) {
			$sanitary_values['foglals_trlse_popup_1'] = esc_textarea( $input['foglals_trlse_popup_1'] );
		}

		if ( isset( $input['last_minute_tooltip_2'] ) ) {
			$sanitary_values['last_minute_tooltip_2'] = esc_textarea( $input['last_minute_tooltip_2'] );
		}

		if ( isset( $input['stteds_tooltip_3'] ) ) {
			$sanitary_values['stteds_tooltip_3'] = esc_textarea( $input['stteds_tooltip_3'] );
		}

		return $sanitary_values;
	}

	public function szvegek_section_info() {
		
	}

	public function sikeres_foglals_popup_0_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="szvegek_option_name[sikeres_foglals_popup_0]" id="sikeres_foglals_popup_0">%s</textarea>',
			isset( $this->szvegek_options['sikeres_foglals_popup_0'] ) ? esc_attr( $this->szvegek_options['sikeres_foglals_popup_0']) : ''
		);
	}

	public function foglals_trlse_popup_1_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="szvegek_option_name[foglals_trlse_popup_1]" id="foglals_trlse_popup_1">%s</textarea>',
			isset( $this->szvegek_options['foglals_trlse_popup_1'] ) ? esc_attr( $this->szvegek_options['foglals_trlse_popup_1']) : ''
		);
	}

	public function last_minute_tooltip_2_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="szvegek_option_name[last_minute_tooltip_2]" id="last_minute_tooltip_2">%s</textarea>',
			isset( $this->szvegek_options['last_minute_tooltip_2'] ) ? esc_attr( $this->szvegek_options['last_minute_tooltip_2']) : ''
		);
	}

	public function stteds_tooltip_3_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="szvegek_option_name[stteds_tooltip_3]" id="stteds_tooltip_3">%s</textarea>',
			isset( $this->szvegek_options['stteds_tooltip_3'] ) ? esc_attr( $this->szvegek_options['stteds_tooltip_3']) : ''
		);
	}

}
if ( is_admin() )
	$szvegek = new Szvegek();

/* 
 * Retrieve this value with:
 * $szvegek_options = get_option( 'szvegek_option_name' ); // Array of All Options
 * $sikeres_foglals_popup_0 = $szvegek_options['sikeres_foglals_popup_0']; // Sikeres foglalás popup
 * $foglals_trlse_popup_1 = $szvegek_options['foglals_trlse_popup_1']; // Foglalás törlése popup
 * $last_minute_tooltip_2 = $szvegek_options['last_minute_tooltip_2']; // Last minute tooltip
 * $stteds_tooltip_3 = $szvegek_options['stteds_tooltip_3']; // Sötétedés tooltip
 */
